{
  "formatVersion": "1.1",
  "component": {
    "group": "org.lubo",
    "module": "gradlePublish",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gradlePublish-3.0.0.jar",
          "url": "gradlePublish-3.0.0.jar",
          "size": 1053,
          "sha512": "b0d48f659aeb2b9c768461a1ad2f29437c0d7895709985e00996c703c10f6756167c5915e708450016c8a6d25084c9fae92103f749e9d72c61cee3f929827159",
          "sha256": "2151498d324b32e0188f3226abed0d6c6bafc0585772f528c9194a13b661a7a5",
          "sha1": "5fc6e09ced297cca68e1d0393aca7697fc18a0fd",
          "md5": "719b56611780e7012e56b2006f1a4745"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.kafka",
          "module": "spring-kafka",
          "version": {
            "requires": "3.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "gradlePublish-3.0.0.jar",
          "url": "gradlePublish-3.0.0.jar",
          "size": 1053,
          "sha512": "b0d48f659aeb2b9c768461a1ad2f29437c0d7895709985e00996c703c10f6756167c5915e708450016c8a6d25084c9fae92103f749e9d72c61cee3f929827159",
          "sha256": "2151498d324b32e0188f3226abed0d6c6bafc0585772f528c9194a13b661a7a5",
          "sha1": "5fc6e09ced297cca68e1d0393aca7697fc18a0fd",
          "md5": "719b56611780e7012e56b2006f1a4745"
        }
      ]
    }
  ]
}
