{
  "formatVersion": "1.1",
  "component": {
    "group": "org.lubo",
    "module": "gradlePublish",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gradlePublish-2.0.0.jar",
          "url": "gradlePublish-2.0.0.jar",
          "size": 907,
          "sha512": "13ee8db80153207da68862b651f4a2f7e46d6bbff91de51995aac4ac87c9062c42f4528bd6555b503ad319a8a832de69577df497321efb2a3112eb49f292c597",
          "sha256": "96d9c955b4ef8dc2672bc1943c08662fd8921db5b6573efe45e5890d42ee6254",
          "sha1": "db9c40fc84c55d4c15c0e73bb5f2f02ec97f6f1f",
          "md5": "9c2b259c2cb18e1da7050df67d51ce73"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradlePublish-2.0.0.jar",
          "url": "gradlePublish-2.0.0.jar",
          "size": 907,
          "sha512": "13ee8db80153207da68862b651f4a2f7e46d6bbff91de51995aac4ac87c9062c42f4528bd6555b503ad319a8a832de69577df497321efb2a3112eb49f292c597",
          "sha256": "96d9c955b4ef8dc2672bc1943c08662fd8921db5b6573efe45e5890d42ee6254",
          "sha1": "db9c40fc84c55d4c15c0e73bb5f2f02ec97f6f1f",
          "md5": "9c2b259c2cb18e1da7050df67d51ce73"
        }
      ]
    }
  ]
}
